### ISSUE TITLE
dotted rests work in Archeage

### ISSUE THREAD

**Issue by kernighan** [smrq/mml-optimizer#1]
The issue with dotted rests in Archeage was fixed in 2.0, many years ago, so the logic around:

noLiteralDottedRests

could be removed since it is no longer relevant.

**Comment by smrq** [comment]
Oh cool. To be honest I dropped Archeage shortly after the original EN launch largely because the MML support was a complete dumpster fire. Did they fix double dotted notes too?

Anywho, I haven't played either of these games in like seven years but I'm happy to merge a MR

**Comment by kernighan** [comment]
They fixed a ton of issues, the real main issue I know that remains is that the length from a previous track is inherited to the next track, so you have to reset it in a new track to the default length of 4 sometimes.  It also still doesn't support "N" midi notes, but that's an easy fix.

I'll play with an MR, right now I'm looking at adapting your code over to python and comparing how it does with optimization vs the optimization built into 3MLE.

I'll double check on the double dotted notes, but IIRC I had a piece recently that used them and it wasn't a problem.

**Comment by smrq** [comment]
Cool, that's not a bad bug really. Extra dots used to grow the length of a note exponentially rather than asymptotically towards 2x (i.e. `..` caused length x1.5x1.5=x2.25 rather than x1.75; `...` was length x3.375 instead of x1.875; etc). This was very very very bad. Client-crashingly bad, potentially.

**Comment by kernighan** [comment]
I ran a track through the optimizer, and unfortunately it came out incorrect.  Input had:

```
r8d+8e8e8e8d8e8e8e8e8e16.r16.e8.e8e2&e8e16r16
```

Output lost the ampersand

```
L8rd+eeedeeeeL16e.r.e8.e8e2e8er
```

Should be:

```
L8rd+eeedeeeeL16e.r.e8.e8e2&e8er
```

**Comment by kernighan** [comment]
Tested using:
```
v127c1..egb,e1&e2&e4gb>e
```

and can confirm ".." works as expected, tracks stayed in sync.  Same with "...". :)

**Comment by kernighan** [comment]
Ok, the & issue is due to the fact that mmlString[0] is the decimal value of the ascii character, not the character.

**Comment by kernighan** [comment]
Ok, there's a bug in how optimization happens if tracksShareState: true and noLiteralDottedRests: false, which didn't surface before because there was no configuration that matched that.
